# Generated by Django 4.2.11 on 2026-01-08 00:00

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0116_alter_stockitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='notes',
            field=InvenTree.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', max_length=50000, null=True, verbose_name='Notes'),
        ),
    ]

