# Generated by Django 4.2.19 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0116_alter_stockitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for this stock location', null=True, verbose_name='Notes'),
        ),
    ]

