# Generated by Django 4.2.19 on 2026-01-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0116_alter_stockitem_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklocation",
            name="notes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Notes",
                help_text="Additional notes or information about this stock location",
            ),
        ),
    ]

